from typing import Any, Protocol

from aeon.core.contracts import CognitiveEvent, MemoryRecord, SelfModel


class Storage(Protocol):
    def append_event(self, event: CognitiveEvent) -> CognitiveEvent: ...
    def list_events(self, limit: int = 200) -> list[CognitiveEvent]: ...
    def save_self_model(self, model: SelfModel) -> None: ...
    def load_self_model(self) -> SelfModel | None: ...
    def save_memory(self, memory: MemoryRecord) -> None: ...
    def list_memories(self) -> list[MemoryRecord]: ...
    def write_record(self, collection: str, record: dict[str, Any]) -> None: ...
    def list_records(self, collection: str) -> list[dict[str, Any]]: ...
